SET search_path TO public;

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Custom Types
--

CREATE TYPE public.statusdoacao AS ENUM (
    'recusado',
    'recebido',
    'lido'
);

CREATE TYPE public.tipocanal AS ENUM (
    'privado',
    'público',
    'misto'
);

--
-- Tables
--

CREATE TABLE public.empresa (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    nome_fantasia text
);

CREATE TABLE public.conversao (
    id_conversao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moeda text NOT NULL UNIQUE,
    nome text NOT NULL,
    fator_conver numeric(18,8) NOT NULL CHECK (fator_conver > 0)
);

CREATE TABLE public.pais (
    id_pais integer GENERATED BY DEFAULT AS IDENTITY,
    ddi integer PRIMARY KEY,
    nome text NOT NULL UNIQUE,
    id_conversao_fk integer NOT NULL REFERENCES public.conversao(id_conversao) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.empresa_pais (
    nro_empresa integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_nacional text,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_empresa, id_pais_fk),
    UNIQUE (id_nacional, id_pais_fk)
);

CREATE TABLE public.plataforma (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    qtd_users integer NOT NULL DEFAULT 0, -- Derivado
    empresa_fund integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    empresa_respo integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    data_fund date NOT NULL
);

CREATE TABLE public.usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick text NOT NULL,
    email text NOT NULL UNIQUE,
    data_nasc date NOT NULL,
    telefone text NOT NULL,
    end_postal text NOT NULL,
    pais_resid text NOT NULL REFERENCES public.pais(nome) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.plataforma_usuario (
    nro_plataforma integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_usuario integer NOT NULL,
    PRIMARY KEY (nro_plataforma, id_usuario_fk)
);

CREATE TABLE public.streamer_pais (
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_passaporte character varying(9) NOT NULL UNIQUE,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id_usuario_fk, id_pais_fk)
);

CREATE TABLE public.canal (
    nro_plataforma integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_canal integer GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    tipo public.tipocanal NOT NULL,
    data date NOT NULL,
    descricao text,
    qtd_visualizacoes bigint DEFAULT 0, -- Derivado
    qtd_videos_postados integer DEFAULT 0, -- Derivado
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma, id_canal)
);

CREATE TABLE public.patrocinio (
    nro_empresa integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_plataforma integer NOT NULL,
    id_canal_fk integer NOT NULL REFERENCES public.canal(id_canal) ON UPDATE CASCADE ON DELETE CASCADE,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    PRIMARY KEY (nro_empresa, nro_plataforma, id_canal_fk),
    FOREIGN KEY (nro_plataforma, id_canal_fk) REFERENCES public.canal(nro_plataforma, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.nivel_canal (
    nro_plataforma integer NOT NULL,
    id_canal_fk integer NOT NULL,
    nivel smallint NOT NULL CHECK (nivel >= 1 AND nivel <= 5),
    nome_nivel text NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    gif bytea,
    PRIMARY KEY (nro_plataforma, id_canal_fk, nivel),
    FOREIGN KEY (nro_plataforma, id_canal_fk) REFERENCES public.canal(nro_plataforma, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.inscricao (
    nro_plataforma integer NOT NULL,
    id_canal_fk integer NOT NULL,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nivel smallint NOT NULL,
    PRIMARY KEY (nro_plataforma, id_canal_fk, id_usuario_fk),
    FOREIGN KEY (nro_plataforma, id_canal_fk, nivel) REFERENCES public.nivel_canal(nro_plataforma, id_canal_fk, nivel) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.video (
    id_video SERIAL PRIMARY KEY,
    nro_plataforma integer NOT NULL,
    id_canal_fk integer NOT NULL,
    titulo text NOT NULL,
    datah timestamp without time zone NOT NULL,
    tema text NOT NULL,
    duracao_segs integer NOT NULL CHECK (duracao_segs > 0),
    visu_simul integer NOT NULL CHECK (visu_simul >= 0),
    visu_total bigint NOT NULL CHECK (visu_total >= 0),
    UNIQUE (nro_plataforma, id_canal_fk, titulo, datah),
    FOREIGN KEY (nro_plataforma, id_canal_fk) REFERENCES public.canal(nro_plataforma, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.participa (
    id_video integer NOT NULL REFERENCES public.video(id_video) ON UPDATE CASCADE ON DELETE CASCADE,
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id_video, id_streamer_fk)
);

CREATE TABLE public.comentario (
    id_comentario SERIAL PRIMARY KEY,
    id_video integer NOT NULL REFERENCES public.video(id_video) ON UPDATE CASCADE ON DELETE CASCADE,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    texto text NOT NULL,
    datah timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    online boolean NOT NULL
);

CREATE TABLE public.doacao (
    id_doacao SERIAL PRIMARY KEY,
    id_comentario integer NOT NULL REFERENCES public.comentario(id_comentario) ON UPDATE CASCADE ON DELETE CASCADE,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    status public.statusdoacao NOT NULL
);

CREATE TABLE public.bitcoin (
    id_doacao integer PRIMARY KEY REFERENCES public.doacao(id_doacao) ON UPDATE CASCADE ON DELETE CASCADE,
    txid text NOT NULL UNIQUE
);

CREATE TABLE public.paypal (
    id_doacao integer PRIMARY KEY REFERENCES public.doacao(id_doacao) ON UPDATE CASCADE ON DELETE CASCADE,
    idpaypal text NOT NULL UNIQUE
);

CREATE TABLE public.cartao_credito (
    id_doacao integer PRIMARY KEY REFERENCES public.doacao(id_doacao) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_cartao text NOT NULL,
    bandeira text NOT NULL
);

CREATE TABLE public.mecanismo_plat (
    id_doacao integer PRIMARY KEY REFERENCES public.doacao(id_doacao) ON UPDATE CASCADE ON DELETE CASCADE,
    seq_plataforma integer NOT NULL
);

--
-- Views (5)
--

-- 1. Streamer Info with Aggregated Stats
CREATE OR REPLACE VIEW public.vw_streamer_info AS
SELECT 
    u.nick,
    u.pais_resid,
    COUNT(DISTINCT c.id_canal) AS total_canais,
    COALESCE(SUM(c.qtd_visualizacoes), 0) AS total_visualizacoes_canais
FROM 
    public.usuario u
LEFT JOIN 
    public.canal c ON u.id_usuario = c.id_streamer_fk
GROUP BY 
    u.nick, u.pais_resid;

-- 2. Canal Stats (Views, Subs, Sponsorship Value)
CREATE OR REPLACE VIEW public.vw_canal_stats AS
SELECT 
    c.nro_plataforma,
    c.nome AS nome_canal,
    c.qtd_visualizacoes,
    COUNT(DISTINCT i.id_usuario_fk) AS total_inscritos,
    COALESCE(SUM(p.valor), 0) AS valor_total_patrocinios
FROM 
    public.canal c
LEFT JOIN 
    public.inscricao i ON c.nro_plataforma = i.nro_plataforma AND c.id_canal = i.id_canal_fk
LEFT JOIN 
    public.patrocinio p ON c.nro_plataforma = p.nro_plataforma AND c.id_canal = p.id_canal_fk
GROUP BY 
    c.nro_plataforma, c.nome, c.qtd_visualizacoes;

-- 3. Video Engagement
CREATE OR REPLACE VIEW public.vw_video_engagement AS
SELECT 
    v.id_video,
    v.titulo,
    v.visu_total,
    COUNT(DISTINCT cm.id_comentario) AS total_comentarios,
    COALESCE(SUM(d.valor), 0) AS total_doacoes
FROM 
    public.video v
LEFT JOIN 
    public.comentario cm ON v.id_video = cm.id_video
LEFT JOIN 
    public.doacao d ON cm.id_comentario = d.id_comentario
GROUP BY 
    v.id_video, v.titulo, v.visu_total;

-- 4. Top Donors
CREATE OR REPLACE VIEW public.vw_top_donors AS
SELECT 
    u.nick,
    u.pais_resid,
    COUNT(d.id_doacao) AS qtd_doacoes,
    SUM(d.valor) AS total_doado
FROM 
    public.usuario u
JOIN 
    public.comentario c ON u.id_usuario = c.id_usuario_fk
JOIN 
    public.doacao d ON c.id_comentario = d.id_comentario
GROUP BY 
    u.nick, u.pais_resid
ORDER BY 
    total_doado DESC;

-- 5. Platform Growth
CREATE OR REPLACE VIEW public.vw_platform_growth AS
SELECT 
    p.nro,
    p.nome,
    p.qtd_users,
    COUNT(DISTINCT c.id_canal) AS qtd_canais,
    COUNT(DISTINCT v.id_video) AS qtd_videos
FROM 
    public.plataforma p
LEFT JOIN 
    public.canal c ON p.nro = c.nro_plataforma
LEFT JOIN 
    public.video v ON c.nro_plataforma = v.nro_plataforma AND c.id_canal = v.id_canal_fk
GROUP BY 
    p.nro, p.nome, p.qtd_users;

--
-- Indices (5)
--

CREATE INDEX idx_video_datah ON public.video(datah);
CREATE INDEX idx_doacao_valor ON public.doacao(valor);
CREATE INDEX idx_usuario_pais ON public.usuario(pais_resid);
CREATE INDEX idx_canal_streamer ON public.canal(id_streamer);
CREATE INDEX idx_comentario_video ON public.comentario(id_video);

--
-- Triggers
--

-- 1. Update Plataforma.qtd_users
CREATE OR REPLACE FUNCTION public.fn_update_qtd_users() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users + 1 WHERE nro = NEW.nro_plataforma;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users - 1 WHERE nro = OLD.nro_plataforma;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_users
AFTER INSERT OR DELETE ON public.plataforma_usuario
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_users();

-- 2. Update Canal.qtd_visualizacoes (when video views update)
CREATE OR REPLACE FUNCTION public.fn_update_qtd_visualizacoes() RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.canal 
    SET qtd_visualizacoes = (
        SELECT COALESCE(SUM(visu_total), 0) 
        FROM public.video 
        WHERE nro_plataforma = NEW.nro_plataforma AND id_canal = NEW.id_canal_fk
    )
    WHERE nro_plataforma = NEW.nro_plataforma AND id_canal = NEW.id_canal_fk;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_visualizacoes
AFTER UPDATE OF visu_total OR INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_visualizacoes();

-- 3. Update Canal.qtd_videos_postados
CREATE OR REPLACE FUNCTION public.fn_update_qtd_videos() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados + 1 
        WHERE nro_plataforma = NEW.nro_plataforma AND id_canal = NEW.id_canal_fk;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados - 1 
        WHERE nro_plataforma = OLD.nro_plataforma AND id_canal = OLD.id_canal_fk;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_videos
AFTER INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_videos();
