SET search_path TO public;

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Custom Types
--

CREATE TYPE public.statusdoacao AS ENUM (
    'recusado',
    'recebido',
    'lido'
);

CREATE TYPE public.tipocanal AS ENUM (
    'privado',
    'público',
    'misto'
);

--
-- Tables
--

CREATE TABLE public.empresa (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    nome_fantasia text
);

CREATE TABLE public.conversao (
    id_conversao SERIAL PRIMARY KEY,
    moeda text NOT NULL UNIQUE,
    nome text NOT NULL,
    fator_conver numeric(18,8) NOT NULL CHECK (fator_conver > 0)
);

CREATE TABLE public.pais (
    id_pais SERIAL PRIMARY KEY,
    ddi integer NOT NULL,
    nome text NOT NULL UNIQUE,
    id_conversao_fk integer NOT NULL REFERENCES public.conversao(id_conversao) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.empresa_pais (
    nro_empresa integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_nacional text,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_empresa, id_pais_fk),
    UNIQUE (id_nacional, id_pais_fk)
);

CREATE TABLE public.plataforma (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    qtd_users integer NOT NULL DEFAULT 0, -- Derivado
    empresa_fund integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    empresa_respo integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    data_fund date NOT NULL
);

CREATE TABLE public.usuario (
    -- id usuário como intenger??
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    data_nasc date NOT NULL,
    telefone text NOT NULL,
    end_postal text NOT NULL,
    id_pais_resid_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.plataforma_usuario (
    nro_plataforma_fk integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_usuario integer NOT NULL,
    PRIMARY KEY (nro_plataforma_fk, id_usuario_fk)
);

CREATE TABLE public.streamer_pais (
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_passaporte character varying(9) NOT NULL UNIQUE,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id_usuario_fk, id_pais_fk)
);

CREATE TABLE public.canal (
    nro_plataforma_fk integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_canal SERIAL,
    nome text NOT NULL,
    tipo public.tipocanal NOT NULL,
    data date NOT NULL,
    descricao text,
    qtd_visualizacoes bigint DEFAULT 0, -- Derivado // mudar bigint futuramente? 
    qtd_videos_postados integer DEFAULT 0, -- Derivado
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_canal)   
);

CREATE TABLE public.patrocinio (
    nro_empresa_fk integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    PRIMARY KEY (nro_empresa_fk, nro_plataforma_fk, id_canal_fk),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.nivel_canal (
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    nivel smallint NOT NULL CHECK (nivel >= 1 AND nivel <= 5),
    nome_nivel text NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    gif bytea,
    PRIMARY KEY (nro_plataforma_fk, id_canal_fk, nivel),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.inscricao (
  id_inscricao integer NOT NULL,
  nro_plataforma_fk integer NOT NULL,
  id_canal_fk integer NOT NULL,
  id_usuario_fk integer NOT NULL,
  nivel smallint NOT NULL,
  CONSTRAINT uq_inscricao_unica UNIQUE (nro_plataforma_fk, id_canal_fk, id_usuario_fk)
) PARTITION BY HASH (nro_plataforma_fk);

-- cria 32 partições com IDENTITY local (cada partição tem sua própria sequence integer)
DO $$
DECLARE i int; n int := 32;
BEGIN
  FOR i IN 0..n-1 LOOP
    EXECUTE format($f$
      CREATE TABLE IF NOT EXISTS public.inscricao_p%1$s PARTITION OF public.inscricao
      FOR VALUES WITH (MODULUS %2$s, REMAINDER %1$s)
      ( id_inscricao SERIAL PRIMARY KEY );
    $f$, i, n);
  END LOOP;
END$$;

CREATE TABLE public.video (
    -- id video pode estourar, melhor usar id canal na pk?
    id_video SERIAL,
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    titulo text NOT NULL,
    datah timestamp without time zone NOT NULL,
    tema text NOT NULL,
    duracao_segs integer NOT NULL CHECK (duracao_segs > 0),
    visu_simul integer NOT NULL CHECK (visu_simul >= 0),
    visu_total bigint NOT NULL CHECK (visu_total >= 0),
    UNIQUE (nro_plataforma_fk, id_canal_fk, titulo, datah),
    PRIMARY KEY (nro_plataforma_fk, id_video),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.participa (
    nro_plataforma_fk integer NOT NULL,
    id_video integer NOT NULL,
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_video, id_streamer_fk),
    FOREIGN KEY (nro_plataforma_fk, id_video) REFERENCES public.video(nro_plataforma_fk, id_video) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.comentario (
    -- id_comentario SERIAL PRIMARY KEY,
    id_video_fk integer NOT NULL,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    texto text NOT NULL,
    nro_plataforma_fk integer NOT NULL,
    seq_comentario integer NOT NULL,
    datah timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    online boolean NOT NULL,
    UNIQUE (nro_plataforma_fk, id_video_fk, seq_comentario),
    FOREIGN KEY (nro_plataforma_fk, id_video_fk) REFERENCES public.video(nro_plataforma_fk, id_video) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_video_fk, seq_comentario)
);

CREATE TABLE public.doacao (
    -- id_comentario_fk integer NOT NULL REFERENCES public.comentario(id_comentario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_plataforma_fk_comentario integer NOT NULL,
    id_video_fk_comentario integer NOT NULL,
    seq_comentario_fk integer NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    status public.statusdoacao NOT NULL,
    PRIMARY KEY (nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk),
    FOREIGN KEY (nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk)
      REFERENCES public.comentario(nro_plataforma_fk, id_video_fk, seq_comentario) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.bitcoin (
    txid text NOT NULL UNIQUE,
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.paypal (
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    idpaypal text NOT NULL UNIQUE,
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.cartao_credito (
    nro_cartao text NOT NULL,
    bandeira text NOT NULL,
    datah timestamp without time zone NOT NULL,
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.mecanismo_plat (
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    seq_plataforma integer NOT NULL,
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao, seq_plataforma),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.comment_counter (
  nro_plataforma_fk integer NOT NULL,
  id_video_fk integer NOT NULL,
  last_seq integer NOT NULL DEFAULT 0,
  PRIMARY KEY (nro_plataforma_fk, id_video_fk)
);

CREATE OR REPLACE FUNCTION public.fn_next_comment_seq(p_nro_plataforma_fk integer, p_id_video_fk integer) RETURNS integer AS $$
DECLARE
  v_seq integer;
BEGIN
  LOOP
    UPDATE public.comment_counter
    SET last_seq = last_seq + 1
    WHERE nro_plataforma_fk = p_nro_plataforma_fk AND id_video_fk = p_id_video_fk
    RETURNING last_seq INTO v_seq;
    IF FOUND THEN
      RETURN v_seq;
    END IF;
    BEGIN
      INSERT INTO public.comment_counter(nro_plataforma_fk, id_video_fk, last_seq)
      VALUES (p_nro_plataforma_fk, p_id_video_fk, 1);
      RETURN 1;
    EXCEPTION WHEN unique_violation THEN
      -- concurrent inserter ganhou; loop para UPDATE
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.fn_assign_seq_comentario() RETURNS trigger AS $$
BEGIN
  IF NEW.seq_comentario IS NULL OR NEW.seq_comentario = 0 THEN
    NEW.seq_comentario := public.fn_next_comment_seq(NEW.nro_plataforma_fk, NEW.id_video_fk);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_assign_seq_comentario ON public.comentario;
CREATE TRIGGER trg_assign_seq_comentario
BEFORE INSERT ON public.comentario
FOR EACH ROW EXECUTE FUNCTION public.fn_assign_seq_comentario();

--
-- Views (5)
--

-- 1) doações por canal (contagens + lidos + valores convertidos)
CREATE OR REPLACE VIEW public.vw_doacoes_por_canal AS
SELECT 
  c.nro_plataforma_fk,
  c.id_canal,
  c.nome AS canal,
  COUNT(d.nro_plataforma_fk_comentario)                           AS total_doacoes,
  SUM(d.valor * COALESCE(cvs.fator_conver,1))                     AS valor_total_doacoes,
  COUNT(d.nro_plataforma_fk_comentario) FILTER (WHERE d.status = 'lido') AS doacoes_lidas,
  SUM(d.valor * COALESCE(cvs.fator_conver,1)) FILTER (WHERE d.status = 'lido') AS valor_doacoes_lidas
FROM public.canal c
JOIN public.video v ON c.nro_plataforma_fk = v.nro_plataforma_fk AND c.id_canal = v.id_canal_fk
JOIN public.comentario cm ON v.nro_plataforma_fk = cm.nro_plataforma_fk AND v.id_video = cm.id_video_fk
JOIN public.doacao d ON cm.nro_plataforma_fk = d.nro_plataforma_fk_comentario
                     AND cm.id_video_fk = d.id_video_fk_comentario
                     AND cm.seq_comentario = d.seq_comentario_fk
LEFT JOIN public.usuario u ON cm.id_usuario_fk = u.id_usuario
LEFT JOIN public.pais pa ON u.id_pais_resid_fk = pa.id_pais
LEFT JOIN public.conversao cvs ON pa.id_conversao_fk = cvs.id_conversao
GROUP BY c.nro_plataforma_fk, c.id_canal, c.nome;

-- 2) inscrições por usuário (CLV / uso frequente) - LEFT JOIN para incluir usuários sem inscrições
CREATE OR REPLACE VIEW public.vw_inscricoes_por_usuario AS
SELECT 
  u.id_usuario,
  u.nick,
  COUNT(i.id_usuario_fk)                            AS total_inscricoes,
  COALESCE(SUM(nc.valor),0)                         AS total_gasto_mensal,
  COUNT(DISTINCT i.nro_plataforma_fk)               AS plataformas_ativas
FROM public.usuario u
LEFT JOIN public.inscricao i ON u.id_usuario = i.id_usuario_fk
LEFT JOIN public.nivel_canal nc ON i.nro_plataforma_fk = nc.nro_plataforma_fk 
  AND i.id_canal_fk = nc.id_canal_fk 
  AND i.nivel = nc.nivel
GROUP BY u.id_usuario, u.nick;

-- 3) patrocínio empresa x canal (rápido filtros empresariais)
CREATE OR REPLACE VIEW public.vw_patrocinio_empresa_canal AS
SELECT 
  e.nro            AS empresa_nro,
  e.nome           AS empresa,
  c.nro_plataforma_fk,
  c.id_canal,
  c.nome           AS canal,
  p.valor          AS valor_patrocinio,
  c.qtd_visualizacoes,
  ROUND(p.valor / NULLIF(c.qtd_visualizacoes, 0) * 1000, 2) AS cpm_estimado
FROM public.patrocinio p
JOIN public.empresa e ON p.nro_empresa_fk = e.nro
JOIN public.canal c ON p.nro_plataforma_fk = c.nro_plataforma_fk AND p.id_canal_fk = c.id_canal;

-- 4) engajamento por vídeo (comentários + doações) - LEFT JOIN para incluir vídeos sem doações/coment
CREATE OR REPLACE VIEW public.vw_engajamento_videos AS
SELECT 
  v.nro_plataforma_fk,
  v.id_video,
  v.titulo,
  c.nome AS canal,
  v.visu_total,
  v.duracao_segs,
  COUNT(cm.seq_comentario)                                   AS total_comentarios,
  COUNT(d.nro_plataforma_fk_comentario)                      AS total_doacoes_video,
  COALESCE(SUM(d.valor * COALESCE(cvs.fator_conver,1)),0)    AS valor_doacoes_video
FROM public.video v
JOIN public.canal c ON v.nro_plataforma_fk = c.nro_plataforma_fk AND v.id_canal_fk = c.id_canal
LEFT JOIN public.comentario cm ON v.nro_plataforma_fk = cm.nro_plataforma_fk AND v.id_video = cm.id_video_fk
LEFT JOIN public.doacao d ON cm.nro_plataforma_fk = d.nro_plataforma_fk_comentario
                         AND cm.id_video_fk = d.id_video_fk_comentario
                         AND cm.seq_comentario = d.seq_comentario_fk
LEFT JOIN public.usuario u ON cm.id_usuario_fk = u.id_usuario
LEFT JOIN public.pais pa ON u.id_pais_resid_fk = pa.id_pais
LEFT JOIN public.conversao cvs ON pa.id_conversao_fk = cvs.id_conversao
GROUP BY v.nro_plataforma_fk, v.id_video, v.titulo, c.nome, v.visu_total, v.duracao_segs;

-- 5) ranking canais (consolida inscritos/patrocínio/inscrições/doações via joins em subagregados)
CREATE OR REPLACE VIEW public.vw_ranking_canais AS
WITH dona AS (
  SELECT v.nro_plataforma_fk, v.id_canal_fk, SUM(d.valor * COALESCE(cvs.fator_conver,1)) AS sum_doacoes
  FROM public.doacao d
  JOIN public.comentario cm ON d.nro_plataforma_fk_comentario = cm.nro_plataforma_fk
                           AND d.id_video_fk_comentario = cm.id_video_fk
                           AND d.seq_comentario_fk = cm.seq_comentario
  JOIN public.video v ON cm.nro_plataforma_fk = v.nro_plataforma_fk AND cm.id_video_fk = v.id_video
  LEFT JOIN public.usuario u ON cm.id_usuario_fk = u.id_usuario
  LEFT JOIN public.pais pa ON u.id_pais_resid_fk = pa.id_pais
  LEFT JOIN public.conversao cvs ON pa.id_conversao_fk = cvs.id_conversao
  GROUP BY v.nro_plataforma_fk, v.id_canal_fk
),
insc AS (
  SELECT i.nro_plataforma_fk, i.id_canal_fk, COUNT(i.id_usuario_fk) AS total_inscritos, SUM(nc.valor) AS sum_inscricoes
  FROM public.inscricao i
  JOIN public.nivel_canal nc ON i.nro_plataforma_fk = nc.nro_plataforma_fk
    AND i.id_canal_fk = nc.id_canal_fk AND i.nivel = nc.nivel
  GROUP BY i.nro_plataforma_fk, i.id_canal_fk
),
patr AS (
  SELECT p.nro_plataforma_fk, p.id_canal_fk, SUM(p.valor) AS sum_patroc
  FROM public.patrocinio p
  GROUP BY p.nro_plataforma_fk, p.id_canal_fk
)
SELECT
  c.nro_plataforma_fk,
  c.id_canal,
  c.nome AS canal,
  c.qtd_visualizacoes,
  COALESCE(insc.total_inscritos,0)   AS total_inscritos,
  COALESCE(patr.sum_patroc,0)       AS total_patrocinios,
  COALESCE(insc.sum_inscricoes,0)   AS total_inscricoes,
  COALESCE(dona.sum_doacoes,0)      AS total_doacoes
FROM public.canal c
LEFT JOIN insc ON c.nro_plataforma_fk = insc.nro_plataforma_fk AND c.id_canal = insc.id_canal_fk
LEFT JOIN patr ON c.nro_plataforma_fk = patr.nro_plataforma_fk AND c.id_canal = patr.id_canal_fk
LEFT JOIN dona ON c.nro_plataforma_fk = dona.nro_plataforma_fk AND c.id_canal = dona.id_canal_fk
ORDER BY (COALESCE(patr.sum_patroc,0) + COALESCE(insc.sum_inscricoes,0) + COALESCE(dona.sum_doacoes,0)) DESC;

--
-- Indices (5)
--

-- 1) acelerar join doacao -> comentario e filtros por status
CREATE INDEX IF NOT EXISTS idx_doacao_coment_scope_status ON public.doacao (nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk, status);

-- 2) acelerar join comentario -> video (usado em doações por vídeo/canal)
CREATE INDEX IF NOT EXISTS idx_comentario_video ON public.comentario (nro_plataforma_fk, id_video_fk);

-- 3) acelerar join video -> canal (usado em quase todas as agregações por canal)
CREATE INDEX IF NOT EXISTS idx_video_canal ON public.video (nro_plataforma_fk, id_canal_fk);

-- 4) acelerar consultas por usuário (CLV / inscrições por usuário)
-- CREATE INDEX IF NOT EXISTS idx_inscricao_usuario ON public.inscricao (id_usuario_fk);

-- índice sugerido (5 índices limitados: este é um dos selecionados)
CREATE INDEX IF NOT EXISTS idx_inscricao_usuario ON public.inscricao (id_usuario_fk);

-- 5) acelerar join usuario -> pais -> conversao (conversão de moeda em agregações)
CREATE INDEX IF NOT EXISTS idx_usuario_pais ON public.usuario (id_pais_resid_fk);

--
-- Triggers
--

-- 1. Update Plataforma.qtd_users
CREATE OR REPLACE FUNCTION public.fn_update_qtd_users() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users + 1 WHERE nro = NEW.nro_plataforma_fk;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users - 1 WHERE nro = OLD.nro_plataforma_fk;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_users
AFTER INSERT OR DELETE ON public.plataforma_usuario
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_users();

-- 2. Update Canal.qtd_visualizacoes (when video views update)
CREATE OR REPLACE FUNCTION public.fn_update_qtd_visualizacoes() RETURNS TRIGGER AS $$
DECLARE
  rec RECORD;
BEGIN
  IF TG_OP = 'DELETE' THEN
    rec := OLD;
  ELSE
    rec := NEW;
  END IF;

  UPDATE public.canal 
  SET qtd_visualizacoes = (
    SELECT COALESCE(SUM(visu_total),0)
    FROM public.video
    WHERE nro_plataforma_fk = rec.nro_plataforma_fk AND id_canal_fk = rec.id_canal_fk
  )
  WHERE nro_plataforma_fk = rec.nro_plataforma_fk AND id_canal = rec.id_canal_fk;

  RETURN rec;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_visualizacoes
AFTER UPDATE OF visu_total OR INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_visualizacoes();

-- 3. Update Canal.qtd_videos_postados
CREATE OR REPLACE FUNCTION public.fn_update_qtd_videos() RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados + 1 
    WHERE nro_plataforma_fk = NEW.nro_plataforma_fk AND id_canal = NEW.id_canal_fk;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados - 1 
    WHERE nro_plataforma_fk = OLD.nro_plataforma_fk AND id_canal = OLD.id_canal_fk;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_videos
AFTER INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_videos();
