SET search_path TO public;

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Custom Types
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'statusdoacao') THEN
    CREATE TYPE public.statusdoacao AS ENUM ('recusado','recebido','lido');
  END IF;
END$$;

CREATE TYPE public.tipocanal AS ENUM (
    'privado',
    'público',
    'misto'
);

--
-- Tables
--

CREATE TABLE public.empresa (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    nome_fantasia text
);

CREATE TABLE public.conversao (
    id_conversao SERIAL PRIMARY KEY,
    moeda text NOT NULL UNIQUE,
    nome text NOT NULL,
    fator_conver numeric(18,8) NOT NULL CHECK (fator_conver > 0)
);

CREATE TABLE public.pais (
    id_pais SERIAL PRIMARY KEY,
    ddi integer NOT NULL,
    nome text NOT NULL UNIQUE,
    id_conversao_fk integer NOT NULL REFERENCES public.conversao(id_conversao) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.empresa_pais (
    nro_empresa integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_nacional text,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_empresa, id_pais_fk),
    UNIQUE (id_nacional, id_pais_fk)
);

CREATE TABLE public.plataforma (
    nro SERIAL PRIMARY KEY,
    nome text NOT NULL,
    qtd_users integer NOT NULL DEFAULT 0, -- Derivado
    empresa_fund integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    empresa_respo integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    data_fund date NOT NULL
);

CREATE TABLE public.usuario (
    -- id usuário como intenger??
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    data_nasc date NOT NULL,
    telefone text NOT NULL,
    end_postal text NOT NULL,
    id_pais_resid_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.plataforma_usuario (
    nro_plataforma_fk integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_usuario integer NOT NULL,
    PRIMARY KEY (nro_plataforma_fk, id_usuario_fk)
);

CREATE TABLE public.streamer_pais (
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_passaporte character varying(9) NOT NULL UNIQUE,
    id_pais_fk integer NOT NULL REFERENCES public.pais(id_pais) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id_usuario_fk, id_pais_fk)
);

CREATE TABLE public.canal (
    nro_plataforma_fk integer NOT NULL REFERENCES public.plataforma(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_canal SERIAL,
    nome text NOT NULL,
    tipo public.tipocanal NOT NULL,
    data date NOT NULL,
    descricao text,
    qtd_visualizacoes bigint DEFAULT 0, -- Derivado // mudar bigint futuramente? 
    qtd_videos_postados integer DEFAULT 0, -- Derivado
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_canal),
    UNIQUE (nro_plataforma_fk, nome)  -- garantir unicidade do nome por plataforma
);

CREATE TABLE public.patrocinio (
    nro_empresa_fk integer NOT NULL REFERENCES public.empresa(nro) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    PRIMARY KEY (nro_empresa_fk, nro_plataforma_fk, id_canal_fk),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.nivel_canal (
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    nivel smallint NOT NULL CHECK (nivel >= 1 AND nivel <= 5),
    nome_nivel text NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    gif bytea,
    PRIMARY KEY (nro_plataforma_fk, id_canal_fk, nivel),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.inscricao (
  nro_plataforma_fk integer NOT NULL,
  id_canal_fk integer NOT NULL,
  id_usuario_fk integer NOT NULL,
  nivel smallint NOT NULL,
  PRIMARY KEY (nro_plataforma_fk, id_canal_fk, id_usuario_fk),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk, nivel) REFERENCES public.nivel_canal(nro_plataforma_fk, id_canal_fk, nivel) ON UPDATE CASCADE ON DELETE RESTRICT
);  
CREATE TABLE public.video (
    -- id video pode estourar, melhor usar id canal na pk?
    id_video SERIAL,
    nro_plataforma_fk integer NOT NULL,
    id_canal_fk integer NOT NULL,
    titulo text NOT NULL,
    datah timestamp without time zone NOT NULL,
    tema text NOT NULL,
    duracao_segs integer NOT NULL CHECK (duracao_segs > 0),
    visu_simul integer NOT NULL CHECK (visu_simul >= 0),
    visu_total bigint NOT NULL CHECK (visu_total >= 0),
    UNIQUE (nro_plataforma_fk, id_canal_fk, titulo, datah),
    PRIMARY KEY (nro_plataforma_fk, id_video),
    FOREIGN KEY (nro_plataforma_fk, id_canal_fk) REFERENCES public.canal(nro_plataforma_fk, id_canal) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.participa (
    nro_plataforma_fk integer NOT NULL,
    id_video_fk integer NOT NULL,
    id_streamer_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_video_fk, id_streamer_fk),
    FOREIGN KEY (nro_plataforma_fk, id_video_fk) REFERENCES public.video(nro_plataforma_fk, id_video) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.comentario (
    -- id_comentario SERIAL PRIMARY KEY,
    id_video_fk integer NOT NULL,
    id_usuario_fk integer NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    texto text NOT NULL,
    nro_plataforma_fk integer NOT NULL,
    seq_comentario integer NOT NULL,
    datah timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    online boolean NOT NULL,
    UNIQUE (nro_plataforma_fk, id_video_fk, seq_comentario),
    FOREIGN KEY (nro_plataforma_fk, id_video_fk) REFERENCES public.video(nro_plataforma_fk, id_video) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (nro_plataforma_fk, id_video_fk, seq_comentario)
) PARTITION BY HASH (nro_plataforma_fk);

-- Partições Comentario (32)
DO $$
DECLARE i int; n int := 32;
BEGIN
  FOR i IN 0..n-1 LOOP
    EXECUTE format($f$
      CREATE TABLE IF NOT EXISTS public.comentario_p%1$s PARTITION OF public.comentario
      FOR VALUES WITH (MODULUS %2$s, REMAINDER %1$s);
    $f$, i, n);
  END LOOP;
END$$;

CREATE TABLE public.doacao (
    -- id_comentario_fk integer NOT NULL REFERENCES public.comentario(id_comentario) ON UPDATE CASCADE ON DELETE CASCADE,
    nro_plataforma_fk_comentario integer NOT NULL,
    id_video_fk_comentario integer NOT NULL,
    seq_comentario_fk integer NOT NULL,
    valor numeric(18,2) NOT NULL CHECK (valor > 0),
    status public.statusdoacao NOT NULL,
    PRIMARY KEY (nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk),
    FOREIGN KEY (nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk)
      REFERENCES public.comentario(nro_plataforma_fk, id_video_fk, seq_comentario) ON UPDATE CASCADE ON DELETE CASCADE
) PARTITION BY HASH (nro_plataforma_fk_comentario);

-- Partições Doacao (32)
DO $$
DECLARE i int; n int := 32;
BEGIN
  FOR i IN 0..n-1 LOOP
    EXECUTE format($f$
      CREATE TABLE IF NOT EXISTS public.doacao_p%1$s PARTITION OF public.doacao
      FOR VALUES WITH (MODULUS %2$s, REMAINDER %1$s);
    $f$, i, n);
  END LOOP;
END$$;

CREATE TABLE public.bitcoin (
    txid text NOT NULL UNIQUE,
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.paypal (
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    idpaypal text NOT NULL UNIQUE,
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.cartao_credito (
    nro_cartao text NOT NULL,
    bandeira text NOT NULL,
    datah timestamp without time zone NOT NULL,
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.mecanismo_plat (
    nro_plataforma_fk_doacao integer NOT NULL,
    id_video_fk_doacao integer NOT NULL,
    seq_comentario_fk_doacao integer NOT NULL,    
    seq_plataforma integer NOT NULL,
    PRIMARY KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao, seq_plataforma),
    FOREIGN KEY (nro_plataforma_fk_doacao, id_video_fk_doacao, seq_comentario_fk_doacao)
      REFERENCES public.doacao(nro_plataforma_fk_comentario, id_video_fk_comentario, seq_comentario_fk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.comment_counter (
  nro_plataforma_fk integer NOT NULL,
  id_video_fk integer NOT NULL,
  last_seq integer NOT NULL DEFAULT 0,
  PRIMARY KEY (nro_plataforma_fk, id_video_fk)
);

CREATE OR REPLACE FUNCTION public.fn_next_comment_seq(p_nro_plataforma_fk integer, p_id_video_fk integer) RETURNS integer AS $$
DECLARE
  v_seq integer;
BEGIN
  LOOP
    UPDATE public.comment_counter
    SET last_seq = last_seq + 1
    WHERE nro_plataforma_fk = p_nro_plataforma_fk AND id_video_fk = p_id_video_fk
    RETURNING last_seq INTO v_seq;
    IF FOUND THEN
      RETURN v_seq;
    END IF;
    BEGIN
      INSERT INTO public.comment_counter(nro_plataforma_fk, id_video_fk, last_seq)
      VALUES (p_nro_plataforma_fk, p_id_video_fk, 1);
      RETURN 1;
    EXCEPTION WHEN unique_violation THEN
      -- concurrent inserter ganhou; loop para UPDATE
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.fn_assign_seq_comentario() RETURNS trigger AS $$
BEGIN
  IF NEW.seq_comentario IS NULL OR NEW.seq_comentario = 0 THEN
    NEW.seq_comentario := public.fn_next_comment_seq(NEW.nro_plataforma_fk, NEW.id_video_fk);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_assign_seq_comentario ON public.comentario;
CREATE TRIGGER trg_assign_seq_comentario
BEFORE INSERT ON public.comentario
FOR EACH ROW EXECUTE FUNCTION public.fn_assign_seq_comentario();

--
-- Views (5) - Otimizadas para Queries
--

-- 1) vw_resumo_financeiro_canal: Agrega total de doações, patrocínios e inscrições por canal.
-- Suporta Query 8 (Ranking Faturamento) e auxiliares.
CREATE OR REPLACE VIEW public.vw_resumo_financeiro_canal AS
WITH patrocinios AS (
    SELECT nro_plataforma_fk, id_canal_fk, SUM(valor) AS total
    FROM public.patrocinio
    GROUP BY nro_plataforma_fk, id_canal_fk
),
inscricoes AS (
    SELECT i.nro_plataforma_fk, i.id_canal_fk, SUM(nc.valor) AS total, COUNT(i.id_usuario_fk) AS qtd_membros
    FROM public.inscricao i
    JOIN public.nivel_canal nc
      ON i.nro_plataforma_fk = nc.nro_plataforma_fk
     AND i.id_canal_fk = nc.id_canal_fk
     AND i.nivel = nc.nivel
    GROUP BY i.nro_plataforma_fk, i.id_canal_fk
),
doacoes AS (
    SELECT
        v.nro_plataforma_fk,
        v.id_canal_fk,
        SUM(d.valor * COALESCE(cvs.fator_conver, 1)) AS total,
        COUNT(*) AS qtd_doacoes
    FROM public.doacao d
    JOIN public.comentario co
      ON d.nro_plataforma_fk_comentario = co.nro_plataforma_fk
     AND d.id_video_fk_comentario = co.id_video_fk
     AND d.seq_comentario_fk = co.seq_comentario
    JOIN public.video v
      ON co.nro_plataforma_fk = v.nro_plataforma_fk
     AND co.id_video_fk = v.id_video
    LEFT JOIN public.usuario u
      ON co.id_usuario_fk = u.id_usuario
    LEFT JOIN public.pais pa
      ON u.id_pais_resid_fk = pa.id_pais
    LEFT JOIN public.conversao cvs
      ON pa.id_conversao_fk = cvs.id_conversao
    WHERE d.status <> 'recusado'
    GROUP BY v.nro_plataforma_fk, v.id_canal_fk
)
SELECT
    c.nro_plataforma_fk,
    c.id_canal,
    c.nome,
    COALESCE(p.total, 0) AS total_patrocinio_USD,
    COALESCE(i.total, 0) AS total_inscricao_USD,
    ROUND(COALESCE(d.total, 0), 2) AS total_doacao_USD,
    (COALESCE(p.total, 0) + COALESCE(i.total, 0) + ROUND(COALESCE(d.total, 0), 2)) AS total_USD,
    COALESCE(i.qtd_membros, 0) AS qtd_membros,
    COALESCE(d.qtd_doacoes, 0) AS qtd_doacoes
FROM public.canal c
LEFT JOIN patrocinios p
  ON c.nro_plataforma_fk = p.nro_plataforma_fk
 AND c.id_canal = p.id_canal_fk
LEFT JOIN inscricoes i
  ON c.nro_plataforma_fk = i.nro_plataforma_fk
 AND c.id_canal = i.id_canal_fk
LEFT JOIN doacoes d
  ON c.nro_plataforma_fk = d.nro_plataforma_fk
 AND c.id_canal = d.id_canal_fk;

-- 2) vw_detalhe_video_engajamento: Agrega views, comentários e doações por vídeo.
-- Suporta Query 3, 4, 7.
CREATE OR REPLACE VIEW public.vw_detalhe_video_engajamento AS
SELECT 
    v.nro_plataforma_fk,
    v.id_video,
    v.titulo,
    v.datah,
    c.nome AS nome_canal,
    COUNT(DISTINCT co.seq_comentario) AS total_comentarios,
    COUNT(d.seq_comentario_fk) AS total_doacoes, -- Count donations
    ROUND(SUM(CASE WHEN d.status = 'lido' THEN d.valor * COALESCE(cvs.fator_conver, 1) ELSE 0 END), 2) AS valor_doacoes_lidas_USD,
    ROUND(SUM(d.valor * COALESCE(cvs.fator_conver, 1)), 2) AS valor_total_doacoes_USD
FROM public.video v
JOIN public.canal c ON v.nro_plataforma_fk = c.nro_plataforma_fk AND v.id_canal_fk = c.id_canal
LEFT JOIN public.comentario co ON v.nro_plataforma_fk = co.nro_plataforma_fk AND v.id_video = co.id_video_fk
LEFT JOIN public.doacao d ON co.nro_plataforma_fk = d.nro_plataforma_fk_comentario 
                          AND co.id_video_fk = d.id_video_fk_comentario 
                          AND co.seq_comentario = d.seq_comentario_fk
LEFT JOIN public.usuario u ON co.id_usuario_fk = u.id_usuario
LEFT JOIN public.pais pa ON u.id_pais_resid_fk = pa.id_pais
LEFT JOIN public.conversao cvs ON pa.id_conversao_fk = cvs.id_conversao
GROUP BY v.nro_plataforma_fk, v.id_video, v.titulo, v.datah, c.nome;

-- 3) vw_usuario_stats: Agrega gastos e inscrições por usuário.
-- Suporta Query 2.
CREATE OR REPLACE VIEW public.vw_usuario_stats AS
SELECT 
    u.id_usuario,
    u.nick,
    COUNT(i.id_canal_fk) AS total_canais_inscrito,
    ROUND(SUM(nc.valor * cvs.fator_conver), 2) AS total_gasto_mensal_USD
FROM public.usuario u
JOIN public.pais p ON u.id_pais_resid_fk = p.id_pais
JOIN public.conversao cvs ON p.id_conversao_fk = cvs.id_conversao
LEFT JOIN public.inscricao i ON u.id_usuario = i.id_usuario_fk
LEFT JOIN public.nivel_canal nc ON i.nro_plataforma_fk = nc.nro_plataforma_fk 
                                AND i.id_canal_fk = nc.id_canal_fk 
                                AND i.nivel = nc.nivel
GROUP BY u.id_usuario, u.nick;

-- 4) vw_patrocinio_stats: Resumo de patrocínios por empresa e canal.
-- Suporta Query 1 e 5.
CREATE OR REPLACE VIEW public.vw_patrocinio_stats AS
SELECT 
    e.nro AS nro_empresa,
    e.nome_fantasia,
    p.nro_plataforma_fk,
    c.nome AS nome_canal,
    p.valor AS valor_USD
FROM public.patrocinio p
JOIN public.empresa e ON p.nro_empresa_fk = e.nro
JOIN public.canal c ON p.nro_plataforma_fk = c.nro_plataforma_fk AND p.id_canal_fk = c.id_canal;

-- 5) vw_ranking_geral: Visão consolidada para rankings rápidos (Top K).
-- Simplifica queries de ranking.
CREATE OR REPLACE VIEW public.vw_ranking_geral AS
SELECT 
    nro_plataforma_fk,
    nome AS nome_canal,
    total_patrocinio_USD,
    total_inscricao_USD,
    total_doacao_USD,
    total_USD,
    qtd_membros,
    qtd_doacoes
FROM public.vw_resumo_financeiro_canal;

--
-- Indices (5) - Otimizados para Queries e Joins
--

-- 1) idx_doacao_status_valor: Filtrar doações válidas e somar valores rapidamente.
CREATE INDEX IF NOT EXISTS idx_doacao_status_valor ON public.doacao (status, valor);

-- 2) idx_comentario_video_user: Acelerar JOINs entre Comentario, Video e Usuario.
CREATE INDEX IF NOT EXISTS idx_comentario_video_user ON public.comentario (nro_plataforma_fk, id_video_fk, id_usuario_fk);

-- 3) idx_video_data_canal: Ordenação temporal e filtro por canal (usado em relatórios).
CREATE INDEX IF NOT EXISTS idx_video_data_canal ON public.video (nro_plataforma_fk, id_canal_fk, datah);

-- 4) idx_inscricao_plataforma_canal: Agrupar inscritos por canal rapidamente.
CREATE INDEX IF NOT EXISTS idx_inscricao_plataforma_canal ON public.inscricao (nro_plataforma_fk, id_canal_fk);

-- 5) idx_patrocinio_valor: Rankings de patrocínio (ORDER BY valor DESC).
CREATE INDEX IF NOT EXISTS idx_patrocinio_valor ON public.patrocinio (valor DESC);

--
-- Triggers
--

-- 1. Update Plataforma.qtd_users
CREATE OR REPLACE FUNCTION public.fn_update_qtd_users() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users + 1 WHERE nro = NEW.nro_plataforma_fk;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.plataforma SET qtd_users = qtd_users - 1 WHERE nro = OLD.nro_plataforma_fk;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_users
AFTER INSERT OR DELETE ON public.plataforma_usuario
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_users();

-- 2. Update Canal.qtd_visualizacoes (when video views update)
CREATE OR REPLACE FUNCTION public.fn_update_qtd_visualizacoes() RETURNS TRIGGER AS $$
DECLARE
  rec RECORD;
BEGIN
  IF TG_OP = 'DELETE' THEN
    rec := OLD;
  ELSE
    rec := NEW;
  END IF;

  UPDATE public.canal 
  SET qtd_visualizacoes = (
    SELECT COALESCE(SUM(visu_total),0)
    FROM public.video
    WHERE nro_plataforma_fk = rec.nro_plataforma_fk AND id_canal_fk = rec.id_canal_fk
  )
  WHERE nro_plataforma_fk = rec.nro_plataforma_fk AND id_canal = rec.id_canal_fk;

  RETURN rec;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_visualizacoes
AFTER UPDATE OF visu_total OR INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_visualizacoes();

-- 3. Update Canal.qtd_videos_postados
CREATE OR REPLACE FUNCTION public.fn_update_qtd_videos() RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados + 1 
    WHERE nro_plataforma_fk = NEW.nro_plataforma_fk AND id_canal = NEW.id_canal_fk;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.canal SET qtd_videos_postados = qtd_videos_postados - 1 
    WHERE nro_plataforma_fk = OLD.nro_plataforma_fk AND id_canal = OLD.id_canal_fk;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_qtd_videos
AFTER INSERT OR DELETE ON public.video
FOR EACH ROW EXECUTE FUNCTION public.fn_update_qtd_videos();
